/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ApiAccessClaimRouteImport } from './routes/api/access/claim'
import { Route as ApiAccessConfigureLinkRouteImport } from './routes/api/access/configure-link'
import { Route as ApiAccessGuideRouteImport } from './routes/api/access/guide'
import { Route as ApiAccessStatusRouteImport } from './routes/api/access/status'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessClaimRoute = ApiAccessClaimRouteImport.update({
  id: '/api/access/claim',
  path: '/api/access/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessConfigureLinkRoute = ApiAccessConfigureLinkRouteImport.update({
  id: '/api/access/configure-link',
  path: '/api/access/configure-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessGuideRoute = ApiAccessGuideRouteImport.update({
  id: '/api/access/guide',
  path: '/api/access/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessStatusRoute = ApiAccessStatusRouteImport.update({
  id: '/api/access/status',
  path: '/api/access/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/api/access/claim': typeof ApiAccessClaimRoute
  '/api/access/configure-link': typeof ApiAccessConfigureLinkRoute
  '/api/access/guide': typeof ApiAccessGuideRoute
  '/api/access/status': typeof ApiAccessStatusRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/api/access/claim': typeof ApiAccessClaimRoute
  '/api/access/configure-link': typeof ApiAccessConfigureLinkRoute
  '/api/access/guide': typeof ApiAccessGuideRoute
  '/api/access/status': typeof ApiAccessStatusRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guide': typeof GuideRoute
  '/api/access/claim': typeof ApiAccessClaimRoute
  '/api/access/configure-link': typeof ApiAccessConfigureLinkRoute
  '/api/access/guide': typeof ApiAccessGuideRoute
  '/api/access/status': typeof ApiAccessStatusRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guide'
    | '/api/access/claim'
    | '/api/access/configure-link'
    | '/api/access/guide'
    | '/api/access/status'
    | '/api/public/razorpay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guide'
    | '/api/access/claim'
    | '/api/access/configure-link'
    | '/api/access/guide'
    | '/api/access/status'
    | '/api/public/razorpay/webhook'
  id:
    | '__root__'
    | '/'
    | '/guide'
    | '/api/access/claim'
    | '/api/access/configure-link'
    | '/api/access/guide'
    | '/api/access/status'
    | '/api/public/razorpay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuideRoute: typeof GuideRoute
  ApiAccessClaimRoute: typeof ApiAccessClaimRoute
  ApiAccessConfigureLinkRoute: typeof ApiAccessConfigureLinkRoute
  ApiAccessGuideRoute: typeof ApiAccessGuideRoute
  ApiAccessStatusRoute: typeof ApiAccessStatusRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/claim': {
      id: '/api/access/claim'
      path: '/api/access/claim'
      fullPath: '/api/access/claim'
      preLoaderRoute: typeof ApiAccessClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/configure-link': {
      id: '/api/access/configure-link'
      path: '/api/access/configure-link'
      fullPath: '/api/access/configure-link'
      preLoaderRoute: typeof ApiAccessConfigureLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/guide': {
      id: '/api/access/guide'
      path: '/api/access/guide'
      fullPath: '/api/access/guide'
      preLoaderRoute: typeof ApiAccessGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/status': {
      id: '/api/access/status'
      path: '/api/access/status'
      fullPath: '/api/access/status'
      preLoaderRoute: typeof ApiAccessStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuideRoute: GuideRoute,
  ApiAccessClaimRoute: ApiAccessClaimRoute,
  ApiAccessConfigureLinkRoute: ApiAccessConfigureLinkRoute,
  ApiAccessGuideRoute: ApiAccessGuideRoute,
  ApiAccessStatusRoute: ApiAccessStatusRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
